# 使用Yaml文件作为配置文件

app_name: 一个应用名
app_key: base64:mIIRo13uoF/m0Oze81WmlLLQxzGcMZVL+Gr0qSKhivc=
version: 0.0.1

# 日期格式
date_format: 2006-01-02 15:04:05

# 运行模式
# 跟进运行环境进行配置
# 开发环境： development
# 测试环境： testing
# 生产环境： production
run_mode: development

jwt:
  timeout: 120    # Jwt过期时间（分钟）
  refresh: 120    # Jwt最大刷新有效期（分钟）

log:
  path: /data/logs/deploy     # 日志路径
  name: deploy                # 日志文件名
  cron_name: cron             # 定时任务日志
  level: 5                    # 日志等级 trace,debug,info,warn,error,fatal,panic
  mode: daily                 # 日志模式 daily 每天
